FROM ubuntu:22.04

RUN mkdir -p /opt/zoomhub
WORKDIR /opt/zoomhub

RUN apt-get upgrade --yes && \
  apt-get update --yes && \
  apt-get install --yes \
  ca-certificates \
  libgmp-dev \
  libpq-dev \
  postgresql-client

ADD run.sh /opt/zoomhub
ADD version.txt /opt/zoomhub
ADD public /opt/zoomhub/public
ADD zoomhub /opt/zoomhub

ADD migrate-database /opt/zoomhub

EXPOSE 8000

ENTRYPOINT ["sh", "-c", "/opt/zoomhub/run.sh"]
