FROM ubuntu:16.04

RUN mkdir -p /opt/app
WORKDIR /opt/app

RUN apt-get update && apt-get install -y \
  ca-certificates \
  libgmp-dev

ADD public /opt/app/public
ADD zoomhub /opt/app

EXPOSE 5000

CMD ["/opt/app/zoomhub"]
