#!/bin/bash


# Commands
case "$1" in
install)
    npm install
    ;;
ping)
    ansible -i deployment/hosts all -m ping
    ;;
deploy)
    ansible-playbook -i deployment/hosts -k deployment/deploy.yml
    ;;
setup)
    ansible-playbook -i deployment/hosts -k deployment/setup.yml
    ;;
*)
    echo "Unknown command: $1. Try: ping|deploy|setup"
    ;;
esac
