#!/bin/bash


# Commands
case "$1" in
install)
    npm install
    ;;
run)
    ./node_modules/.bin/_coffee app._coffee
    ;;
ping)
    ansible --user zoomhub --inventory-file deployment/hosts all -m ping
    ;;
bootstrap)
    echo "Enter root password when prompted"
    ansible-playbook --inventory-file deployment/hosts \
                     --ask-pass deployment/bootstrap.yml
    ;;
setup)
    ansible-playbook --inventory-file deployment/hosts deployment/setup.yml
    ;;
deploy)
    ansible-playbook --inventory-file deployment/hosts deployment/deploy.yml
    ;;
*)
    echo "Unknown command: $1. Try: bootstrap|ping|setup|deploy"
    ;;
esac
