module ZoomHub.Types.Content
  ( Content
  , contentId
  , contentType
  , contentURL
  , contentState
  , contentInitializedAt
  , contentActiveAt
  , contentCompletedAt
  , contentMIME
  , contentSize
  , contentProgress
  , contentNumViews
  , contentError
  , contentDZI
  , ContentSubmission(..)
  ) where

import ZoomHub.Types.Content.Internal
  ( Content
  , ContentSubmission(..)
  , contentActiveAt
  , contentCompletedAt
  , contentDZI
  , contentError
  , contentId
  , contentInitializedAt
  , contentMIME
  , contentNumViews
  , contentProgress
  , contentSize
  , contentState
  , contentType
  , contentURL
  )
