module ZoomHub.Types.Content
  ( Content,
    contentId,
    contentType,
    contentURL,
    contentState,
    contentInitializedAt,
    contentActiveAt,
    contentCompletedAt,
    contentMIME,
    contentSize,
    contentProgress,
    contentNumViews,
    contentError,
    contentDZI,
    contentSubmitterEmail,
  )
where

import ZoomHub.Types.Content.Internal
  ( Content,
    contentActiveAt,
    contentCompletedAt,
    contentDZI,
    contentError,
    contentId,
    contentInitializedAt,
    contentMIME,
    contentNumViews,
    contentProgress,
    contentSize,
    contentState,
    contentSubmitterEmail,
    contentType,
    contentURL,
  )
